export const BUSINESS_SECTORS = [
  { code: "technology", name: "Technology" },
  { code: "healthcare", name: "Healthcare" },
  { code: "finance", name: "Finance" },
  { code: "education", name: "Education" },
  { code: "retail", name: "Retail" },
  { code: "manufacturing", name: "Manufacturing" },
  { code: "real-estate", name: "Real Estate" },
  { code: "transportation", name: "Transportation" },
  { code: "energy", name: "Energy" },
  { code: "entertainment", name: "Entertainment" },
  { code: "food-and-beverage", name: "Food and Beverage" },
  { code: "automotive", name: "Automotive" },
  { code: "construction", name: "Construction" },
  { code: "agriculture", name: "Agriculture" },
  { code: "mining", name: "Mining" },
  { code: "oil-and-gas", name: "Oil and Gas" },
  { code: "pharmaceuticals", name: "Pharmaceuticals" },
  { code: "biotechnology", name: "Biotechnology" },
];
